list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/tools)
set(X_AGENT_INCLUDE_DIRS ${PROJECT_SOURCE_DIR}/include)

if(${CMAKE_SYSTEM_PROCESSOR} MATCHES "x86_64")
  set(ARCH "x86")
elseif(${CMAKE_SYSTEM_PROCESSOR} MATCHES "arm")
  set(ARCH "arm")
elseif(${CMAKE_SYSTEM_PROCESSOR} MATCHES "aarch64")
  set(ARCH "arm64")
elseif(${CMAKE_SYSTEM_PROCESSOR} MATCHES "ppc64le")
  set(ARCH "powerpc")
elseif(${CMAKE_SYSTEM_PROCESSOR} MATCHES "mips")
  set(ARCH "mips")
elseif(${CMAKE_SYSTEM_PROCESSOR} MATCHES "riscv64")
  set(ARCH "riscv")
elseif(${CMAKE_SYSTEM_PROCESSOR} MATCHES "loongarch64")
  set(ARCH "loongarch")
endif()

find_package(BpfObject REQUIRED)

add_executable(bootstrap)
bpf_object(bootstrap ${PROJECT_SOURCE_DIR}/src/bootstrap.bpf.c)
target_sources(bootstrap PRIVATE ${PROJECT_SOURCE_DIR}/src/bootstrap.c)
target_include_directories(bootstrap PRIVATE ${X_AGENT_INCLUDE_DIRS})
target_link_libraries(bootstrap PRIVATE bootstrap_skel)